package me.dizzykitty3.androidtoolkitty

// Android intents
const val S_DISPLAY = "setting_display"
const val S_AUTO_ROTATE = "setting_auto_rotate"
const val S_BLUETOOTH = "setting_bluetooth"
const val S_DEFAULT_APPS = "setting_default_apps"
const val S_BATTERY_OPTIMIZATION = "setting_battery_optimization"
const val S_CAPTION = "setting_caption"
const val S_USAGE_ACCESS = "setting_usage_access"
const val S_OVERLAY = "setting_overlay"
const val S_MODIFY_SYSTEM = "setting_modify_system"
const val S_LOCALE = "setting_locale"
const val S_DATE = "setting_date"
const val S_DEVELOPER = "setting_developer"
const val S_ENABLE_BLUETOOTH = "setting_enable_bluetooth"
const val S_WIFI = "setting_wifi"
const val S_BATTERY = "setting_battery"
const val S_ACCESSIBILITY = "setting_accessibility"
const val S_NOTIFICATION_LISTENER = "setting_notification_listener"
const val S_DND_ACCESS = "setting_dnd_access"
const val S_UNKNOWN_APPS = "setting_unknown_apps"
const val S_ALARMS = "setting_alarms"
const val S_MEDIA_MANAGEMENT = "setting_media_management"
const val S_APP_NOTIFICATIONS = "setting_app_notifications"
const val S_ACCOUNTS = "setting_accounts"
const val S_VPN = "setting_vpn"
const val S_SEARCH_SETTINGS = "setting_search_settings"
const val S_SOUND = "setting_sound"
const val S_ABOUT_PHONE = "setting_about_phone"
const val S_KEYBOARD = "setting_keyboard"
const val S_NFC = "setting_nfc"
