package me.dizzykitty3.androidtoolkitty

// URL
const val HTTPS = "https://"
const val BG = ".bg"
const val CN = ".cn"
const val CO_AR = ".co.ar"
const val CO_JP = ".co.jp"
const val CO_UK = ".co.uk"
const val COM = ".com"
const val COM_CN = ".com.cn"
const val EE = ".ee"
const val IR = ".ir"
const val JP = ".jp"
const val LA = ".la"
const val NET = ".net"
const val ME = ".me"
const val MX = ".mx"
const val NZ = ".nz"
const val ORG = ".org"
const val RU = ".ru"
const val SO = ".so"
const val TO = ".to"
const val TV = ".tv"
const val US = ".us"
const val WIKI = ".wiki"
const val SOURCE_CODE_URL = "https://github.com/dizzykitty3/AndroidToolKitty"
